volumes:
  data:

networks:
  default:
  
services:

  #
  # Storage services
  #

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql
    networks:
      - default

  #
  # Authorization services
  #

  permify:
    image: ghcr.io/permify/permify:latest
    ports:
      - 3476:3476 # used by HTTP service
      #- 3478:3478 # used by GRPC service
    volumes:
      - ./permify/config.yaml:/etc/agent/config.river
    command: serve
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/permify
      - PORT=/migrations
    networks:
      - default

  loki:
      image: grafana/loki:2.9.4
      ports:
        - "3100:3100"
      command: -config.file=/etc/loki/local-config.yaml
      networks:
        - default

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - default

  agent:
    image: grafana/agent:latest
    ports:
      - "12345:12345"
    volumes:
      - ./agent/config.river:/etc/agent/config.river
    environment:
      - AGENT_MODE=flow
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/agent/config.river
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      - default